[build]
  base = "client"
  publish = "build"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://game-zone-production-6354.up.railway.app"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://game-zone-production-6354.up.railway.app"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://game-zone-production-6354.up.railway.app"
