services:
  - type: web
    name: gamezone-social
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://game-zone-production-6354.up.railway.app
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
