services:
  - type: web
    name: gamezone-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RIOT_API_KEY
        sync: false
    healthCheckPath: /
